Retry logic (#67)
* Do not exit script on error of logs command

* Retry logic on revision creation

* More debug messages

* Implement retries for init revision creation too

* Fix variable reference

* Fetch depth 0

* Timeout on init run in case we get stuck in infinite loop

diff --git a/.github/actions/azure-container-apps-deploy-and-run-init/action.yml b/.github/actions/azure-container-apps-deploy-and-run-init/action.yml
--- a/.github/actions/azure-container-apps-deploy-and-run-init/action.yml
+++ b/.github/actions/azure-container-apps-deploy-and-run-init/action.yml
@@ -45,10 +45,23 @@ runs:
       with:
         inlineScript: |
           echo Creating new revision of ${{ inputs.INIT_CONTAINER_APP_JOB }} Container App Job...
-          az containerapp job update \
-            --resource-group ${{ inputs.RESOURCE_GROUP }} \
-            --name ${{ inputs.INIT_CONTAINER_APP_JOB }} \
-            --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.INIT_IMAGE }}:${{ github.run_id }}
+          retries=0
+          while [[ $retries < 3 ]]; do
+            az containerapp job update \
+              --resource-group ${{ inputs.RESOURCE_GROUP }} \
+              --name ${{ inputs.INIT_CONTAINER_APP_JOB }} \
+              --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.INIT_IMAGE }}:${{ github.run_id }} \
+              || true # do not exit the script on error
+            status=$?
+            if [[ $status != 0 ]]; then
+              echo Revision creation failed, retrying...
+              retries=$((retries + 1))
+              continue
+            else
+              exit 0
+            fi 
+          done
+          echo Failed to create revision!
 
     - name: Run init job
       uses: azure/cli@v2
@@ -89,7 +102,8 @@ runs:
               --name ${{ inputs.INIT_CONTAINER_APP_JOB }} \
               --execution $executionName \
               --container ${{ inputs.INIT_CONTAINER_NAME }} \
-              --follow true
+              --follow true \
+              || true # do not exit the script on error
 
             executionStatus=$(get_execution_status $executionName)
 
diff --git a/.github/actions/azure-container-apps-deploy-revision/action.yml b/.github/actions/azure-container-apps-deploy-revision/action.yml
--- a/.github/actions/azure-container-apps-deploy-revision/action.yml
+++ b/.github/actions/azure-container-apps-deploy-revision/action.yml
@@ -46,11 +46,24 @@ runs:
       with:
         inlineScript: |
           echo Creating new revision of ${{ inputs.CONTAINER_APP }}...
-          az containerapp revision copy \
-            --resource-group ${{ inputs.RESOURCE_GROUP }} \
-            --name ${{ inputs.CONTAINER_APP }} \
-            --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.IMAGE }}:${{ github.run_id }} \
-            --revision-suffix run-${{ github.run_id }}
+          retries=0
+          while [[ $retries < 3 ]]; do
+            az containerapp revision copy \
+              --resource-group ${{ inputs.RESOURCE_GROUP }} \
+              --name ${{ inputs.CONTAINER_APP }} \
+              --image ${{ inputs.CONTAINER_REGISTRY }}/${{ inputs.IMAGE }}:${{ github.run_id }} \
+              --revision-suffix run-${{ github.run_id }} \
+              || true # do not exit the script on error
+            status=$?
+            if [[ $status != 0 ]]; then
+              echo Revision creation failed, retrying...
+              retries=$((retries + 1))
+              continue
+            else
+              exit 0
+            fi 
+          done
+          echo Failed to create revision!
 
     - name: If using a multi-revision setup, ensure that 100% of traffic is set to the latest...
       uses: azure/cli@v2
