Consolidate Pimcore secrets for 2025.x and fix unit tests in CI (#108)
* Build+push now expects explicit Pimcore secrets

* Send Pimcore secrets to unit tests runtime

* CI - explicit secrets for new 2025.x Pimcore secrets

* Meta tests for 2024.x and 2025.x

* Workflwo naming

* Required secrets for 2025.x

* Remove comments from secrets array

* Test against unit test branch

* Add all required env vars for Pimcore install

* Build classes if DataObject directory doesn't exist or is empty

* Run tests with codeception by default and fallback to PHPUnit

* Change skeleton branch

* Run against 2025.x

diff --git a/.github/actions/run-unit-tests/action.yml b/.github/actions/run-unit-tests/action.yml
--- a/.github/actions/run-unit-tests/action.yml
+++ b/.github/actions/run-unit-tests/action.yml
@@ -12,13 +12,22 @@ inputs:
     description: "A JSON object containing a list of args and their values in key: value format"
   BUILD_TIME_SECRETS:
     required: true
-    description: "JSON object containing a list of secrets and their values in key: value format"
+    description: "JSON object containing a list of build-time secrets and their values in key: value format"
   PIMCORE_ROOT:
     required: true
     description: "The path (relative to the project's root) in which the Pimcore files exist"
   PIMCORE_ENTERPRISE_TOKEN:
     required: false
     description: "The value of your project's Pimcore Enterprise Token"
+  PIMCORE_PRODUCT_KEY:
+    required: false
+    description: (Optional) The Pimcore product key for the project
+  PIMCORE_INSTANCE_IDENTIFIER:
+    required: false
+    description: (Optional) The Pimcore instance identifier for the project
+  PIMCORE_ENCRYPTION_SECRET:
+    required: false
+    description: (Optional) The Pimcore encryption secret for the project
   TORQ_GITHUB_TOKEN:
     required: false
     description: "A GitHub access token used to access private GitHub repositories"
@@ -61,6 +70,9 @@ runs:
         BUILD_TIME_ARGS: ${{ inputs.BUILD_TIME_ARGS }}
         BUILD_TIME_SECRETS: ${{ inputs.BUILD_TIME_SECRETS }} 
         PIMCORE_ENTERPRISE_TOKEN: ${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}
+        PIMCORE_PRODUCT_KEY: ${{ inputs.PIMCORE_PRODUCT_KEY }}
+        PIMCORE_INSTANCE_IDENTIFIER: ${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}
+        PIMCORE_ENCRYPTION_SECRET: ${{ inputs.PIMCORE_ENCRYPTION_SECRET }}
         TORQ_GITHUB_TOKEN: ${{ inputs.TORQ_GITHUB_TOKEN }}
         PUSH: "false"
         LOAD: "true"
@@ -80,27 +92,42 @@ runs:
           -e DATABASE_USER=test \
           -e DATABASE_PASSWORD=test \
           -e PIMCORE_TEST_DB_DSN='mysql://test:test@test-db:3306/test' \
+          -e PIMCORE_PRODUCT_KEY='${{ inputs.PIMCORE_PRODUCT_KEY }}' \
+          -e PIMCORE_INSTANCE_IDENTIFIER='${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}' \
+          -e PIMCORE_ENCRYPTION_SECRET='${{ inputs.PIMCORE_ENCRYPTION_SECRET }}' \
+          -e PIMCORE_ENTERPRISE_TOKEN='${{ inputs.PIMCORE_ENTERPRISE_TOKEN }}' \
+          -e PIMCORE_INSTALL_MYSQL_HOST_SOCKET='test-db' \
+          -e PIMCORE_INSTALL_MYSQL_PORT='3306' \
+          -e PIMCORE_INSTALL_MYSQL_USERNAME='test' \
+          -e PIMCORE_INSTALL_MYSQL_PASSWORD='test' \
+          -e PIMCORE_INSTALL_MYSQL_DATABASE='test' \
+          -e PIMCORE_INSTALL_ADMIN_USERNAME='admin' \
+          -e PIMCORE_INSTALL_ADMIN_PASSWORD='pimcore' \
+          -e PIMCORE_INSTALL_ENCRYPTION_SECRET='${{ inputs.PIMCORE_ENCRYPTION_SECRET }}' \
+          -e PIMCORE_INSTALL_INSTANCE_IDENTIFIER='${{ inputs.PIMCORE_INSTANCE_IDENTIFIER }}' \
+          -e PIMCORE_INSTALL_PRODUCT_KEY='${{ inputs.PIMCORE_PRODUCT_KEY }}' \
           --entrypoint /bin/bash \
           init:test \
           -c '
             set -e
             
             echo "Installing Pimcore..."
-            runuser -u www-data -- /var/www/html/vendor/bin/pimcore-install \
-              --admin-username=test \
-              --admin-password=test \
-              --mysql-host-socket=test-db \
-              --mysql-database=test \
-              --mysql-username=test \
-              --mysql-password=test
+            runuser -u www-data -- /var/www/html/vendor/bin/pimcore-install --skip-database-config --no-interaction
 
-            if [ $(ls -A "/var/www/html/var/classes/DataObject" | wc -l) -ne 0 ]; then
+            if [ ! -d "/var/www/html/var/classes/DataObject" ] || [ -z "$(ls -A /var/www/html/var/classes/DataObject 2>/dev/null)" ]; then
               echo "Building Data Object classes..."
               runuser -u www-data -- /var/www/html/bin/console pimcore:build:classes
             fi
             
             echo "Running tests..."
-            runuser -u www-data -- /var/www/html/vendor/bin/phpunit --testdox ${{ inputs.UNIT_TESTS_DIRECTORY }}
+            if [ -f "/var/www/html/vendor/bin/codecept" ]; then
+              runuser -u www-data -- /var/www/html/vendor/bin/codecept run
+            elif [ -f "/var/www/html/vendor/bin/phpunit" ]; then
+              runuser -u www-data -- /var/www/html/vendor/bin/phpunit --testdox ${{ inputs.UNIT_TESTS_DIRECTORY }}
+            else
+              echo "Error: Neither codecept nor phpunit found in vendor/bin"
+              exit 1
+            fi
           '
 
     - name: Cleanup containers
