Feat/new pimcore template changes (#32)
* fix pimcore-root references

* update docker references

* add init container

* Init setup and allowing old workflows to function

* Fixing context of service principal ID

* AZ login

* Typos

* Typo and step namees fix

* Caching init image build

* Using GHA cache in PHP and supervisor options as well

* Upgrading node setup to version 20

* Adding missing PIMCORE_ROOT context to cd frontend call

* Fixing context when moving Node build files

* Trying prefix option instead of cd'ing

---------

Co-authored-by: Evan Jackson <evan.jackson@torqit.ca>

diff --git a/.github/workflows/container-apps-build-and-deploy.yml b/.github/workflows/container-apps-build-and-deploy.yml
--- a/.github/workflows/container-apps-build-and-deploy.yml
+++ b/.github/workflows/container-apps-build-and-deploy.yml
@@ -26,6 +26,30 @@ on:
         required: false
         type: boolean
         default: false
+      INIT:
+        required: false
+        type: boolean
+        default: false
+      PIMCORE_ROOT:
+        required: false
+        type: string
+        default: 'pimcore-root'
+      PHP_DOCKERFILE:
+        required: false
+        type: string
+        default: 'docker/php-fpm/Dockerfile'
+      PHP_DOCKER_TARGET:
+        required: false
+        type: string
+        default: ''
+      SUPERVISORD_DOCKERFILE:
+        required: false
+        type: string
+        default: 'docker/supervisord/Dockerfile'
+      SUPERVISORD_TARGET:
+        required: false
+        type: string
+        default: ''
 
     secrets:
       SERVICE_PRINCIPAL_ID:
@@ -38,11 +62,113 @@ on:
         required: false
 
 jobs:
-  build-and-deploy-php-fpm:
+  run-init-job:
+    if: ${{ inputs.INIT }}
     runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
     environment: ${{ inputs.ENVIRONMENT }}
 
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Copy in database.yaml file
+        run: cp ${{ inputs.PIMCORE_ROOT }}/config/db/database-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/database.yaml
+
+      - name: Log in to Azure Container Registry ${{ vars.CONTAINER_REGISTRY }}
+        uses: docker/login-action@v2
+        with:
+          registry: ${{ vars.CONTAINER_REGISTRY }}
+          username: "${{ secrets.SERVICE_PRINCIPAL_ID }}"
+          password: "${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}"
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Set up Docker Buildx
+        id: buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: .docker/Dockerfile
+          target: init
+          push: true
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          tags: |
+            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.INIT_IMAGE }}:latest,
+            ${{ vars.CONTAINER_REGISTRY }}/${{ vars.INIT_IMAGE }}:${{ github.run_id }}
+
+      - name: Log into Azure CLI
+        run: |
+          echo Logging into Azure...
+          az login \
+            --tenant ${{ vars.TENANT }} \
+            --service-principal \
+            --username '${{ secrets.SERVICE_PRINCIPAL_ID }}' \
+            --password '${{ secrets.SERVICE_PRINCIPAL_PASSWORD }}'
+      
+      - name: Install Azure CLI containerapp extension
+        run: |
+          az config set extension.use_dynamic_install=yes_without_prompt
+          az extension add --name containerapp
+
+      - name: Run init (migration and seeding) Container App Job
+        run: |
+          echo Creating new revision of ${{ vars.INIT_CONTAINER_APP_JOB }} Container App Job
+          az containerapp job update \
+            --resource-group ${{ vars.RESOURCE_GROUP }} \
+            --name ${{ vars.INIT_CONTAINER_APP_JOB }} \
+            --image ${{ vars.CONTAINER_REGISTRY }}/${{ vars.INIT_IMAGE }}:${{ github.run_id }}
+
+          echo Running init Container App Job...
+          az containerapp job start \
+            --resource-group ${{ vars.RESOURCE_GROUP }} \
+            --name ${{ vars.INIT_CONTAINER_APP_JOB }}
+
+          executionName=$(az containerapp job execution list \
+            --resource-group ${{ vars.RESOURCE_GROUP }} \
+            --name ${{ vars.INIT_CONTAINER_APP_JOB }} \
+            | jq -r '.[] | select(.properties.status | contains("Running")) | .name')
+          echo Waiting for $executionName to finish...
+
+          executionStatus=$(az containerapp job execution list \
+            --resource-group ${{ vars.RESOURCE_GROUP }} \
+            --name ${{ vars.INIT_CONTAINER_APP_JOB }} \
+            | jq -r --arg executionName $executionName '.[] | select(.name==$executionName) | .properties.status')
+          while [[ "$executionStatus" == "Running" ]]
+          do
+            echo Job execution $executionName is still running...
+            sleep 5
+            executionStatus=$(az containerapp job execution list \
+              --resource-group ${{ vars.RESOURCE_GROUP }} \
+              --name ${{ vars.INIT_CONTAINER_APP_JOB }} \
+              | jq -r --arg executionName $executionName '.[] | select(.name==$executionName) | .properties.status')
+          done
+
+          if [[ "$executionStatus" == "Succeeded" ]]
+          then
+            echo "Execution $executionName succeeded!"
+          else
+            echo "Execution $executionName failed!"
+            exit 1
+          fi
+
+  build-and-deploy-php-fpm:
+    runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
+    environment: ${{ inputs.ENVIRONMENT }}
+    needs: 
+      - run-init-job
+    if: always()
+
+    steps:
+      # This is a workaround for the fact there is no way to do a conditional "needs"
+      - name: Fail fast if necessary jobs failed
+        if: ${{ needs.run-init-job.result == 'failure' }}
+        run: exit 1
+
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
@@ -51,9 +177,9 @@ jobs:
       - uses: actions/setup-node@v3
         if: ${{ inputs.NPM_BUILD }}
         with:
-          node-version: 16
+          node-version: 20
           cache: 'npm'
-          cache-dependency-path: pimcore-root/frontend/package-lock.json
+          cache-dependency-path: ${{ inputs.PIMCORE_ROOT }}/frontend/package-lock.json
 
       - name: Cache node modules
         id: cache-npm
@@ -73,23 +199,21 @@ jobs:
         env:
           CI: "" # required to ensure warnings aren't treated as errors
         run: |
-          cd pimcore-root/frontend
-          npm ci --legacy-peer-deps
-          npm run ${{ inputs.NPM_RUN_CMD }}
+          npm --prefix ${{ inputs.PIMCORE_ROOT }}/frontend ci --legacy-peer-deps
+          npm --prefix ${{ inputs.PIMCORE_ROOT }}/frontend run ${{ inputs.NPM_RUN_CMD }}
           if ${{ inputs.NPM_SPA }}
           then
-            cd ../../
-            mv pimcore-root/frontend/build/index.html pimcore-root/templates/${{ inputs.SPA_TWIG }}
-            mv pimcore-root/frontend/build/* pimcore-root/public/
+            mv ${{ inputs.PIMCORE_ROOT }}/frontend/build/index.html ${{ inputs.PIMCORE_ROOT }}/templates/${{ inputs.SPA_TWIG }}
+            mv ${{ inputs.PIMCORE_ROOT }}/frontend/build/* ${{ inputs.PIMCORE_ROOT }}/public/
           fi
       
       - name: Copy in database.yaml file
-        run: cp pimcore-root/config/db/database-dev-prod.yaml pimcore-root/config/database.yaml
+        run: cp ${{ inputs.PIMCORE_ROOT }}/config/db/database-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/database.yaml
 
       - name: Copy in flysystem.yaml file
         run: |
-          if [ -e pimcore-root/config/flysystem/flysystem-dev-prod.yaml ]; then
-            cp pimcore-root/config/flysystem/flysystem-dev-prod.yaml pimcore-root/config/packages/flysystem.yaml
+          if [ -e ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ]; then
+            cp ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/packages/flysystem.yaml
           fi
           
       - name: Log in to Azure Container Registry ${{ vars.CONTAINER_REGISTRY }}
@@ -110,8 +234,11 @@ jobs:
         uses: docker/build-push-action@v4
         with:
             context: .
-            file: ./docker/php-fpm/Dockerfile
+            file: ${{ inputs.PHP_DOCKERFILE }}
+            target: ${{ inputs.PHP_DOCKER_TARGET }}
             push: true
+            cache-from: type=gha
+            cache-to: type=gha,mode=max
             tags: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.PHP_FPM_IMAGE }}:latest,
                   ${{ vars.CONTAINER_REGISTRY }}/${{ vars.PHP_FPM_IMAGE }}:${{ github.run_id }}
             build-args: |
@@ -149,20 +276,28 @@ jobs:
   build-and-deploy-supervisord:
     runs-on: ${{ inputs.RUNNER || 'ubuntu-latest' }}
     environment: ${{ inputs.ENVIRONMENT }}
+    needs:
+      - run-init-job
+    if: always()
 
     steps:
+      # This is a workaround for the fact there is no way to do a conditional "needs"
+      - name: Fail fast if necessary jobs failed
+        if: ${{ needs.run-init-job.result == 'failure' }}
+        run: exit 1
+
       - name: Checkout repository
         uses: actions/checkout@v3
         with:
           submodules: ${{ inputs.SUBMODULES }}
 
       - name: Copy in database.yaml file
-        run: cp pimcore-root/config/db/database-dev-prod.yaml pimcore-root/config/database.yaml
+        run: cp ${{ inputs.PIMCORE_ROOT }}/config/db/database-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/database.yaml
 
       - name: Copy in flysystem.yaml file
         run: |
-          if [ -e pimcore-root/config/flysystem/flysystem-dev-prod.yaml ]; then
-            cp pimcore-root/config/flysystem/flysystem-dev-prod.yaml pimcore-root/config/packages/flysystem.yaml
+          if [ -e ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ]; then
+            cp ${{ inputs.PIMCORE_ROOT }}/config/flysystem/flysystem-dev-prod.yaml ${{ inputs.PIMCORE_ROOT }}/config/packages/flysystem.yaml
           fi
 
       - name: Log into Azure Container Registry ${{ vars.CONTAINER_REGISTRY }}
@@ -183,8 +318,11 @@ jobs:
         uses: docker/build-push-action@v4
         with:
             context: .
-            file: ./docker/supervisord/Dockerfile
+            file: ${{ inputs.SUPERVISORD_DOCKERFILE }}
+            target: ${{ inputs.SUPERVISORD_TARGET }}
             push: true
+            cache-from: type=gha
+            cache-to: type=gha,mode=max
             tags: ${{ vars.CONTAINER_REGISTRY }}/${{ vars.SUPERVISORD_IMAGE }}:latest,
                   ${{ vars.CONTAINER_REGISTRY }}/${{ vars.SUPERVISORD_IMAGE }}:${{ github.run_id }}
             build-args: |
